### PR TITLE
switch to JSON web tokens

### LINKED ISSUE #54: Switch to JWTs
We. don't use jwts. and we probably should

### PR DESCRIPTION
**Pull request by nbitzz**
resolves #54

### CODE REVIEW

**Comment by nbitzz** [comment]
should reconsider unless we can use the token hash as its id or something otherwise it might just be easier to jwt

**Comment by nbitzz** [comment]
Still want to do this but these branches are quite divergent now so closing this PR

**Comment by nbitzz** [comment]
This actually seems to work which is shocking

**Review by Jack5079 — APPROVED** [review]
verygood

**Pull request merged**
